# Generated by Django 2.2.2 on 2019-12-04 14:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20191204_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('publish_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8)),
                ('title', models.CharField(max_length=20)),
                ('blog_description', models.CharField(default='NA', max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('author_email', models.EmailField(default='NA', max_length=254)),
                ('author_details', models.CharField(default='NA', max_length=200)),
                ('target_stream', models.CharField(max_length=100)),
                ('blog_text', models.TextField(default='NA')),
                ('head_image', models.ImageField(default='NA', upload_to='')),
                ('relevant_links', models.URLField(default='NA')),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('blogger_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('blogger_since', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('stream_name', models.CharField(max_length=30)),
                ('stream_description', models.CharField(default='NA', max_length=100)),
                ('stream_owner', models.CharField(max_length=20)),
                ('date_of_launch', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
